### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Joshua-G2**
Before issuing a pull request, please see the contributing page.

### CODE REVIEW

**Review by InFrosnito — APPROVED** [review]

**Review by Wildcats6380 — DISMISSED** [review]

**Review by Wildcats6380 — CHANGES_REQUESTED** [review]
This terrible go back to english class

**Comment by Joshua-G2** [comment]
GREAT  I'm glad it works this was just a test

**Review by Joshua-G2 — COMMENTED** [review]
ok

**Comment by InFrosnito** [comment]
u guys are rly rly cardboard boxes

**Pull request closed without merging**
